datasource:
  statistics:
    jdbcUrl: jdbc:mysql://localhost:3306/statistics?zeroDataTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  external:
    jdbcUrl: jdbc:mysql://49.50.161.215:3306/fkream
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always

kafka:
  bootstrapAddress: 49.50.173.232:9092
  group-id: fkream-batch