datasource:
  statistics:
    jdbcUrl: jdbc:mysql://localhost:3306/statistics?zeroDataTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  external:
    jdbcUrl: jdbc:mysql://49.50.161.215:3306/fkream
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: fkream
      username: admin
      password: admin
      auto-index-creation: true
kafka:
  bootstrapAddress: 101.101.210.178:9092, 101.101.210.178:9093, 101.101.210.178:9094
  group-id: fkream_batch
  topic:
    search-log: search_log
    complete-deal-price: complete_deal_price

server:
  port: 9000